version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306
  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
  wordpress:
    container_name: wordpress
    networks:
      - inception
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/html
    
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aherrman/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/aherrman/data/mariadb'

networks:
  inception:
    driver: bridge 